### ISSUE TITLE
Pixel Ordering

### ISSUE THREAD

**Issue by alexmathfb** [sahajgarg/image_transformer#6]
Very nice job, the code is very nice!

**Context.** Autoregressive models (including Image Transformer) can be viewed as a one layer normalizing flow as described in [this article](https://arxiv.org/abs/2002.02547) Section 4. The article contains [code](https://github.com/didriknielsen/pixelcnn_flow) which trains PixelCNN as a flow. I am trying to do the same for Image Transformer by using your implementation. 

**Question 1.** PixelCNN generates in raster scan order. Does your Pixel Transformer implementation also use raster scan order?

https://github.com/sahajgarg/image_transformer/blob/d33b8d007299b434c62e068e1dad35b8a2688212/image_transformer.py#L208
![image](https://user-images.githubusercontent.com/85679431/128512816-9c404042-53b8-460d-ac46-5288795251f8.png)

**Comment by sahajgarg** [comment]
Yes, I use raster scan order, following the paper.  

See here: 
https://github.com/sahajgarg/image_transformer/blob/d33b8d007299b434c62e068e1dad35b8a2688212/image_transformer.py#L85
